apiVersion: v1
kind: Pod
metadata:
  namespace: demoapp
  name: mongo
  labels:
    name: mongo
spec:
  containers:
    -
      name: mongo
      image: mongo:3.4.0
      ports:
        -
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  namespace: demoapp
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: demoapp
  name: myemp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: myemp
    spec:
      containers:
      - name: myemp-dc-pod
        image: prasenforu/employee
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  namespace: demoapp
  name: myemp
  labels:
    name: myemp
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    name: myemp
  type: LoadBalancer
  
