apiVersion: v1
kind: Namespace
metadata:
  name: demomsg
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmqsrv
  namespace: demomsg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmqsrv
  template:
    metadata:
      labels:
        app: rabbitmqsrv
    spec:
      containers:
      - name: rabbitmqsrv-dc-pod
        image: prasenforu/rabbitmq:2.0
        ports:
        - containerPort: 5672
          name: service
        - containerPort: 15672
          name: management
      - image: prasenforu/rabbitmq-exporter:1.0
        name: rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
        env:
        - name: RABBIT_USER
          value: "rabbitmq"
        - name: RABBIT_PASSWORD
          value: "znwk2BaTLAqowMrv"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'
  name: rabbitmqsrv
  namespace: demomsg
  labels:
    app: rabbitmqsrv
spec:
  type: LoadBalancer
  ports:
  - name: 5672-tcp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: 15672-tcp
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: 9090-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: rabbitmqsrv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmqclient
  namespace: demomsg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmqclient
  template:
    metadata:
      labels:
        app: rabbitmqclient
    spec:
      containers:
      - name: rabbitmqclient-dc-pod
        image: prasenforu/mqclient:2.0
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmqclient
  namespace: demomsg
  labels:
    app: rabbitmqclient
spec:
  type: LoadBalancer
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: rabbitmqclient
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmqsrv
  namespace: demomsg
spec:
  endpoints:
  - interval: 5s
    port: 9090-metrics
  selector:
    matchLabels:
      app: rabbitmqsrv
      
